// 80+ Professional Invoice Templates
export interface InvoiceTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  colorScheme: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
  layout: 'classic' | 'modern' | 'minimal' | 'bold' | 'creative' | 'elegant';
  industry: string[];
  previewImage?: string;
}

export const INVOICE_TEMPLATES: InvoiceTemplate[] = [
  // CLASSIC TEMPLATES (1-10)
  {
    id: 'classic-blue-1',
    name: 'Classic Blue Professional',
    category: 'Classic',
    description: 'Traditional invoice with blue header and professional layout',
    layout: 'classic',
    industry: ['Consulting', 'Legal', 'Accounting', 'Professional Services'],
    colorScheme: {
      primary: '#1e3a8a',
      secondary: '#dbeafe',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'classic-green-2',
    name: 'Classic Green Corporate',
    category: 'Classic',
    description: 'Corporate green theme with clean layout',
    layout: 'classic',
    industry: ['Finance', 'Banking', 'Insurance', 'Corporate'],
    colorScheme: {
      primary: '#166534',
      secondary: '#dcfce7',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'classic-navy-3',
    name: 'Navy Business Standard',
    category: 'Classic',
    description: 'Navy blue theme for business invoices',
    layout: 'classic',
    industry: ['Business', 'B2B', 'Corporate'],
    colorScheme: {
      primary: '#0f172a',
      secondary: '#e0e7ff',
      accent: '#4f46e5',
      background: '#ffffff',
      text: '#1e293b',
    },
  },
  {
    id: 'classic-red-4',
    name: 'Classic Red Statement',
    category: 'Classic',
    description: 'Bold red accent for important invoices',
    layout: 'classic',
    industry: ['Marketing', 'Creative', 'Events'],
    colorScheme: {
      primary: '#991b1b',
      secondary: '#fee2e2',
      accent: '#dc2626',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'classic-gray-5',
    name: 'Minimal Gray',
    category: 'Classic',
    description: 'Minimalist gray and white design',
    layout: 'classic',
    industry: ['General', 'All'],
    colorScheme: {
      primary: '#374151',
      secondary: '#f3f4f6',
      accent: '#6b7280',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'classic-purple-6',
    name: 'Purple Professional',
    category: 'Classic',
    description: 'Purple accent for tech and creative industries',
    layout: 'classic',
    industry: ['Technology', 'SaaS', 'Software', 'Creative'],
    colorScheme: {
      primary: '#5b21b6',
      secondary: '#f3e8ff',
      accent: '#a855f7',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'classic-teal-7',
    name: 'Teal Modern Classic',
    category: 'Classic',
    description: 'Teal and white combination for modern businesses',
    layout: 'classic',
    industry: ['Tech', 'Startup', 'Digital'],
    colorScheme: {
      primary: '#134e4a',
      secondary: '#ccfbf1',
      accent: '#14b8a6',
      background: '#ffffff',
      text: '#0f172a',
    },
  },
  {
    id: 'classic-orange-8',
    name: 'Warm Orange Accent',
    category: 'Classic',
    description: 'Warm orange for construction, energy, and trades',
    layout: 'classic',
    industry: ['Construction', 'Energy', 'Trades', 'Manufacturing'],
    colorScheme: {
      primary: '#92400e',
      secondary: '#fed7aa',
      accent: '#f97316',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'classic-indigo-9',
    name: 'Indigo Business',
    category: 'Classic',
    description: 'Deep indigo for financial services',
    layout: 'classic',
    industry: ['Finance', 'Banking', 'Insurance'],
    colorScheme: {
      primary: '#312e81',
      secondary: '#e0e7ff',
      accent: '#6366f1',
      background: '#ffffff',
      text: '#1e1b4b',
    },
  },
  {
    id: 'classic-slate-10',
    name: 'Slate Elegant',
    category: 'Classic',
    description: 'Elegant slate theme for premium services',
    layout: 'classic',
    industry: ['Luxury', 'Premium', 'Consulting'],
    colorScheme: {
      primary: '#1e293b',
      secondary: '#f1f5f9',
      accent: '#64748b',
      background: '#ffffff',
      text: '#0f172a',
    },
  },

  // MODERN TEMPLATES (11-25)
  {
    id: 'modern-gradient-11',
    name: 'Modern Gradient Blue',
    category: 'Modern',
    description: 'Modern design with gradient header',
    layout: 'modern',
    industry: ['Tech', 'SaaS', 'Startup', 'Digital'],
    colorScheme: {
      primary: '#0284c7',
      secondary: '#e0f2fe',
      accent: '#06b6d4',
      background: '#f8fafc',
      text: '#1e293b',
    },
  },
  {
    id: 'modern-split-12',
    name: 'Modern Split Design',
    category: 'Modern',
    description: 'Two-column modern layout',
    layout: 'modern',
    industry: ['Creative', 'Design', 'Tech'],
    colorScheme: {
      primary: '#7c3aed',
      secondary: '#ede9fe',
      accent: '#a78bfa',
      background: '#ffffff',
      text: '#1e1b4b',
    },
  },
  {
    id: 'modern-side-accent-13',
    name: 'Modern Side Accent',
    category: 'Modern',
    description: 'Vertical accent bar on the side',
    layout: 'modern',
    industry: ['Design', 'Marketing', 'Brand'],
    colorScheme: {
      primary: '#ec4899',
      secondary: '#fce7f3',
      accent: '#f43f5e',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'modern-clean-14',
    name: 'Modern Clean White',
    category: 'Modern',
    description: 'Clean white space with modern elements',
    layout: 'modern',
    industry: ['Tech', 'Startup', 'Professional'],
    colorScheme: {
      primary: '#075985',
      secondary: '#e8f1f8',
      accent: '#0ea5e9',
      background: '#ffffff',
      text: '#1e293b',
    },
  },
  {
    id: 'modern-bold-15',
    name: 'Modern Bold Statement',
    category: 'Modern',
    description: 'Bold typography with modern layout',
    layout: 'modern',
    industry: ['Creative', 'Design', 'Agency'],
    colorScheme: {
      primary: '#1f2937',
      secondary: '#f3f4f6',
      accent: '#10b981',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'modern-circle-16',
    name: 'Modern Circle Accent',
    category: 'Modern',
    description: 'Circular design element as accent',
    layout: 'modern',
    industry: ['Tech', 'Marketing', 'Creative'],
    colorScheme: {
      primary: '#dc2626',
      secondary: '#fee2e2',
      accent: '#f87171',
      background: '#ffffff',
      text: '#7f1d1d',
    },
  },
  {
    id: 'modern-minimal-17',
    name: 'Ultra Modern Minimal',
    category: 'Modern',
    description: 'Minimalist modern with maximum white space',
    layout: 'modern',
    industry: ['Design', 'Creative', 'Luxury'],
    colorScheme: {
      primary: '#000000',
      secondary: '#f5f5f5',
      accent: '#808080',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'modern-tech-18',
    name: 'Tech Modern Dark',
    category: 'Modern',
    description: 'Dark modern theme for tech companies',
    layout: 'modern',
    industry: ['Technology', 'SaaS', 'Software'],
    colorScheme: {
      primary: '#1e293b',
      secondary: '#e2e8f0',
      accent: '#00d9ff',
      background: '#f8fafc',
      text: '#1e293b',
    },
  },
  {
    id: 'modern-vibrant-19',
    name: 'Vibrant Modern',
    category: 'Modern',
    description: 'Vibrant colors for creative businesses',
    layout: 'modern',
    industry: ['Creative', 'Marketing', 'Design'],
    colorScheme: {
      primary: '#ff006e',
      secondary: '#ffe8f0',
      accent: '#8338ec',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'modern-pastel-20',
    name: 'Pastel Modern',
    category: 'Modern',
    description: 'Soft pastel colors with modern design',
    layout: 'modern',
    industry: ['Creative', 'Wellness', 'Lifestyle'],
    colorScheme: {
      primary: '#fb7185',
      secondary: '#fecdd3',
      accent: '#fda4af',
      background: '#ffffff',
      text: '#831843',
    },
  },

  // MINIMAL TEMPLATES (21-35)
  {
    id: 'minimal-black-white-21',
    name: 'Minimal Black & White',
    category: 'Minimal',
    description: 'Pure black and white minimal design',
    layout: 'minimal',
    industry: ['Legal', 'Consulting', 'Professional'],
    colorScheme: {
      primary: '#000000',
      secondary: '#ffffff',
      accent: '#666666',
      background: '#ffffff',
      text: '#000000',
    },
  },
  {
    id: 'minimal-monochrome-22',
    name: 'Monochrome Minimal',
    category: 'Minimal',
    description: 'Single color monochrome theme',
    layout: 'minimal',
    industry: ['Professional', 'B2B', 'Corporate'],
    colorScheme: {
      primary: '#4b5563',
      secondary: '#f0f2f5',
      accent: '#4b5563',
      background: '#ffffff',
      text: '#2c3e50',
    },
  },
  {
    id: 'minimal-typeface-23',
    name: 'Typography Focus Minimal',
    category: 'Minimal',
    description: 'Minimal design with typography focus',
    layout: 'minimal',
    industry: ['Design', 'Creative', 'Publishing'],
    colorScheme: {
      primary: '#1a1a1a',
      secondary: '#fafafa',
      accent: '#404040',
      background: '#ffffff',
      text: '#1a1a1a',
    },
  },
  {
    id: 'minimal-grid-24',
    name: 'Grid Minimal',
    category: 'Minimal',
    description: 'Grid-based minimal layout',
    layout: 'minimal',
    industry: ['Tech', 'Digital', 'Startup'],
    colorScheme: {
      primary: '#2563eb',
      secondary: '#eff6ff',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1e40af',
    },
  },
  {
    id: 'minimal-line-25',
    name: 'Line Art Minimal',
    category: 'Minimal',
    description: 'Minimal with line art elements',
    layout: 'minimal',
    industry: ['Design', 'Creative', 'Architecture'],
    colorScheme: {
      primary: '#374151',
      secondary: '#f9fafb',
      accent: '#6b7280',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'minimal-concept-26',
    name: 'Concept Minimal',
    category: 'Minimal',
    description: 'Conceptual minimalist invoice design',
    layout: 'minimal',
    industry: ['Design', 'Art', 'Creative'],
    colorScheme: {
      primary: '#059669',
      secondary: '#ecfdf5',
      accent: '#10b981',
      background: '#ffffff',
      text: '#065f46',
    },
  },
  {
    id: 'minimal-elegant-27',
    name: 'Elegant Minimal',
    category: 'Minimal',
    description: 'Elegant minimal for luxury brands',
    layout: 'minimal',
    industry: ['Luxury', 'Fashion', 'Premium'],
    colorScheme: {
      primary: '#78350f',
      secondary: '#fef3c7',
      accent: '#d97706',
      background: '#ffffff',
      text: '#451a03',
    },
  },
  {
    id: 'minimal-tech-28',
    name: 'Tech Minimal',
    category: 'Minimal',
    description: 'Tech-forward minimal design',
    layout: 'minimal',
    industry: ['Technology', 'SaaS', 'Software'],
    colorScheme: {
      primary: '#0f766e',
      secondary: '#f0fdfa',
      accent: '#14b8a6',
      background: '#ffffff',
      text: '#134e4a',
    },
  },
  {
    id: 'minimal-corporate-29',
    name: 'Corporate Minimal',
    category: 'Minimal',
    description: 'Corporate minimal design',
    layout: 'minimal',
    industry: ['Corporate', 'B2B', 'Enterprise'],
    colorScheme: {
      primary: '#1e3a8a',
      secondary: '#eff6ff',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1e40af',
    },
  },
  {
    id: 'minimal-zen-30',
    name: 'Zen Minimal',
    category: 'Minimal',
    description: 'Zen-inspired minimal design',
    layout: 'minimal',
    industry: ['Wellness', 'Health', 'Coaching'],
    colorScheme: {
      primary: '#7c2d12',
      secondary: '#ede9fe',
      accent: '#92400e',
      background: '#ffffff',
      text: '#5b21b6',
    },
  },

  // BOLD TEMPLATES (31-45)
  {
    id: 'bold-neon-31',
    name: 'Bold Neon Electric',
    category: 'Bold',
    description: 'Bold neon colors for tech and creative',
    layout: 'bold',
    industry: ['Tech', 'Creative', 'Entertainment'],
    colorScheme: {
      primary: '#1f2937',
      secondary: '#00ff00',
      accent: '#00ffff',
      background: '#000000',
      text: '#ffffff',
    },
  },
  {
    id: 'bold-dark-32',
    name: 'Bold Dark Mode',
    category: 'Bold',
    description: 'Bold dark theme with bright accents',
    layout: 'bold',
    industry: ['Creative', 'Tech', 'Design'],
    colorScheme: {
      primary: '#1a1a1a',
      secondary: '#2d2d2d',
      accent: '#ff0080',
      background: '#0a0a0a',
      text: '#ffffff',
    },
  },
  {
    id: 'bold-red-impact-33',
    name: 'Bold Red Impact',
    category: 'Bold',
    description: 'Bold red for high-impact invoices',
    layout: 'bold',
    industry: ['Marketing', 'Sales', 'Events'],
    colorScheme: {
      primary: '#b91c1c',
      secondary: '#fecaca',
      accent: '#dc2626',
      background: '#ffffff',
      text: '#7f1d1d',
    },
  },
  {
    id: 'bold-gold-34',
    name: 'Bold Gold Premium',
    category: 'Bold',
    description: 'Bold gold for premium services',
    layout: 'bold',
    industry: ['Luxury', 'Premium', 'High-end'],
    colorScheme: {
      primary: '#78350f',
      secondary: '#fef3c7',
      accent: '#fbbf24',
      background: '#ffffff',
      text: '#451a03',
    },
  },
  {
    id: 'bold-purple-35',
    name: 'Bold Purple Royalty',
    category: 'Bold',
    description: 'Bold purple for premium brands',
    layout: 'bold',
    industry: ['Premium', 'Luxury', 'Exclusive'],
    colorScheme: {
      primary: '#6b21a8',
      secondary: '#f3e8ff',
      accent: '#d946ef',
      background: '#ffffff',
      text: '#581c87',
    },
  },
  {
    id: 'bold-teal-36',
    name: 'Bold Teal Statement',
    category: 'Bold',
    description: 'Bold teal for modern businesses',
    layout: 'bold',
    industry: ['Tech', 'Innovation', 'Startup'],
    colorScheme: {
      primary: '#0d9488',
      secondary: '#ccfbf1',
      accent: '#06b6d4',
      background: '#ffffff',
      text: '#134e4a',
    },
  },
  {
    id: 'bold-navy-37',
    name: 'Bold Navy Statement',
    category: 'Bold',
    description: 'Bold navy for professional impact',
    layout: 'bold',
    industry: ['Finance', 'Banking', 'Corporate'],
    colorScheme: {
      primary: '#001f3f',
      secondary: '#e8f1f8',
      accent: '#003d82',
      background: '#ffffff',
      text: '#1e293b',
    },
  },
  {
    id: 'bold-orange-38',
    name: 'Bold Orange Energy',
    category: 'Bold',
    description: 'Bold orange for energetic brands',
    layout: 'bold',
    industry: ['Energy', 'Construction', 'Trades'],
    colorScheme: {
      primary: '#b45309',
      secondary: '#fcd34d',
      accent: '#f97316',
      background: '#ffffff',
      text: '#78350f',
    },
  },
  {
    id: 'bold-green-39',
    name: 'Bold Green Growth',
    category: 'Bold',
    description: 'Bold green for sustainable businesses',
    layout: 'bold',
    industry: ['Eco', 'Green', 'Sustainability'],
    colorScheme: {
      primary: '#15803d',
      secondary: '#dcfce7',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#166534',
    },
  },
  {
    id: 'bold-pink-40',
    name: 'Bold Pink Statement',
    category: 'Bold',
    description: 'Bold pink for creative and fashion',
    layout: 'bold',
    industry: ['Fashion', 'Beauty', 'Creative'],
    colorScheme: {
      primary: '#be185d',
      secondary: '#fbcfe8',
      accent: '#ec4899',
      background: '#ffffff',
      text: '#831843',
    },
  },

  // ELEGANT TEMPLATES (41-55)
  {
    id: 'elegant-gold-frame-41',
    name: 'Elegant Gold Frame',
    category: 'Elegant',
    description: 'Elegant design with gold frame',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'Wedding'],
    colorScheme: {
      primary: '#78350f',
      secondary: '#fef3c7',
      accent: '#d97706',
      background: '#fffbeb',
      text: '#451a03',
    },
  },
  {
    id: 'elegant-silver-42',
    name: 'Elegant Silver Luxury',
    category: 'Elegant',
    description: 'Silver theme for luxury services',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'Exclusive'],
    colorScheme: {
      primary: '#374151',
      secondary: '#f3f4f6',
      accent: '#9ca3af',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'elegant-marble-43',
    name: 'Elegant Marble',
    category: 'Elegant',
    description: 'Marble texture elegant design',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'High-end'],
    colorScheme: {
      primary: '#1f2937',
      secondary: '#f9fafb',
      accent: '#d1d5db',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'elegant-rose-44',
    name: 'Elegant Rose Gold',
    category: 'Elegant',
    description: 'Rose gold elegant design',
    layout: 'elegant',
    industry: ['Luxury', 'Beauty', 'Fashion'],
    colorScheme: {
      primary: '#92400e',
      secondary: '#fef2f2',
      accent: '#d97706',
      background: '#ffffff',
      text: '#78350f',
    },
  },
  {
    id: 'elegant-navy-gold-45',
    name: 'Navy & Gold Elegant',
    category: 'Elegant',
    description: 'Navy and gold combination for elegance',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'Consulting'],
    colorScheme: {
      primary: '#001f3f',
      secondary: '#e8f1f8',
      accent: '#d97706',
      background: '#ffffff',
      text: '#1e293b',
    },
  },
  {
    id: 'elegant-classic-46',
    name: 'Elegant Classic',
    category: 'Elegant',
    description: 'Timeless elegant classic design',
    layout: 'elegant',
    industry: ['Professional', 'Consulting', 'Legal'],
    colorScheme: {
      primary: '#1e1e1e',
      secondary: '#f5f5f5',
      accent: '#505050',
      background: '#ffffff',
      text: '#1a1a1a',
    },
  },
  {
    id: 'elegant-burgundy-47',
    name: 'Elegant Burgundy',
    category: 'Elegant',
    description: 'Burgundy theme for elegant services',
    layout: 'elegant',
    industry: ['Wine', 'Luxury', 'Premium'],
    colorScheme: {
      primary: '#6b1d1d',
      secondary: '#fee2e2',
      accent: '#a00000',
      background: '#ffffff',
      text: '#4b0000',
    },
  },
  {
    id: 'elegant-teal-48',
    name: 'Elegant Teal',
    category: 'Elegant',
    description: 'Elegant teal for upscale services',
    layout: 'elegant',
    industry: ['Spa', 'Wellness', 'Premium'],
    colorScheme: {
      primary: '#134e4a',
      secondary: '#ccfbf1',
      accent: '#0f766e',
      background: '#ffffff',
      text: '#134e4a',
    },
  },
  {
    id: 'elegant-indigo-49',
    name: 'Elegant Indigo',
    category: 'Elegant',
    description: 'Indigo elegant for premium brands',
    layout: 'elegant',
    industry: ['Premium', 'Luxury', 'High-end'],
    colorScheme: {
      primary: '#312e81',
      secondary: '#e0e7ff',
      accent: '#6366f1',
      background: '#ffffff',
      text: '#1e1b4b',
    },
  },
  {
    id: 'elegant-pearl-50',
    name: 'Elegant Pearl',
    category: 'Elegant',
    description: 'Pearl white elegant design',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'Exclusive'],
    colorScheme: {
      primary: '#2c2c2c',
      secondary: '#f8f8f8',
      accent: '#b8b8b8',
      background: '#ffffff',
      text: '#1a1a1a',
    },
  },

  // CREATIVE TEMPLATES (51-65)
  {
    id: 'creative-rainbow-51',
    name: 'Creative Rainbow',
    category: 'Creative',
    description: 'Rainbow colors for creative businesses',
    layout: 'creative',
    industry: ['Creative', 'Design', 'Entertainment'],
    colorScheme: {
      primary: '#ff0000',
      secondary: '#ffe8e8',
      accent: '#00ff00',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'creative-gradient-52',
    name: 'Creative Gradient Flow',
    category: 'Creative',
    description: 'Flowing gradient creative design',
    layout: 'creative',
    industry: ['Creative', 'Agency', 'Digital'],
    colorScheme: {
      primary: '#7c3aed',
      secondary: '#f3e8ff',
      accent: '#ec4899',
      background: '#ffffff',
      text: '#1e1b4b',
    },
  },
  {
    id: 'creative-geometric-53',
    name: 'Creative Geometric',
    category: 'Creative',
    description: 'Geometric shapes and patterns',
    layout: 'creative',
    industry: ['Design', 'Creative', 'Tech'],
    colorScheme: {
      primary: '#1f2937',
      secondary: '#f3f4f6',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'creative-vibrant-54',
    name: 'Vibrant Creative',
    category: 'Creative',
    description: 'Vibrant colors for creative impact',
    layout: 'creative',
    industry: ['Creative', 'Marketing', 'Events'],
    colorScheme: {
      primary: '#ff006e',
      secondary: '#ffe8f0',
      accent: '#8338ec',
      background: '#ffffff',
      text: '#381a52',
    },
  },
  {
    id: 'creative-playful-55',
    name: 'Playful Creative',
    category: 'Creative',
    description: 'Playful design for creative brands',
    layout: 'creative',
    industry: ['Creative', 'Kids', 'Entertainment'],
    colorScheme: {
      primary: '#f59e0b',
      secondary: '#fef3c7',
      accent: '#fbbf24',
      background: '#ffffff',
      text: '#78350f',
    },
  },
  {
    id: 'creative-artistic-56',
    name: 'Artistic Canvas',
    category: 'Creative',
    description: 'Art-inspired creative invoice',
    layout: 'creative',
    industry: ['Art', 'Creative', 'Gallery'],
    colorScheme: {
      primary: '#5b21b6',
      secondary: '#f3e8ff',
      accent: '#a855f7',
      background: '#ffffff',
      text: '#2e1065',
    },
  },
  {
    id: 'creative-music-57',
    name: 'Music Creative',
    category: 'Creative',
    description: 'Music and entertainment theme',
    layout: 'creative',
    industry: ['Music', 'Entertainment', 'Events'],
    colorScheme: {
      primary: '#be185d',
      secondary: '#fbcfe8',
      accent: '#ec4899',
      background: '#ffffff',
      text: '#831843',
    },
  },
  {
    id: 'creative-nature-58',
    name: 'Nature Creative',
    category: 'Creative',
    description: 'Nature-inspired creative design',
    layout: 'creative',
    industry: ['Nature', 'Eco', 'Green'],
    colorScheme: {
      primary: '#15803d',
      secondary: '#dcfce7',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#166534',
    },
  },
  {
    id: 'creative-urban-59',
    name: 'Urban Creative',
    category: 'Creative',
    description: 'Urban street art inspired',
    layout: 'creative',
    industry: ['Urban', 'Creative', 'Art'],
    colorScheme: {
      primary: '#1f2937',
      secondary: '#f3f4f6',
      accent: '#06b6d4',
      background: '#ffffff',
      text: '#111827',
    },
  },
  {
    id: 'creative-fashion-60',
    name: 'Fashion Creative',
    category: 'Creative',
    description: 'Fashion industry creative design',
    layout: 'creative',
    industry: ['Fashion', 'Beauty', 'Luxury'],
    colorScheme: {
      primary: '#000000',
      secondary: '#f5f5f5',
      accent: '#ff00ff',
      background: '#ffffff',
      text: '#000000',
    },
  },

  // INDUSTRY-SPECIFIC TEMPLATES (61-80)
  {
    id: 'industry-tech-61',
    name: 'Tech Startup SaaS',
    category: 'Industry Specific',
    description: 'Perfect for tech and SaaS companies',
    layout: 'modern',
    industry: ['Technology', 'SaaS', 'Startup'],
    colorScheme: {
      primary: '#0284c7',
      secondary: '#e0f2fe',
      accent: '#0ea5e9',
      background: '#f8fafc',
      text: '#1e293b',
    },
  },
  {
    id: 'industry-medical-62',
    name: 'Medical Healthcare',
    category: 'Industry Specific',
    description: 'Healthcare and medical invoices',
    layout: 'classic',
    industry: ['Healthcare', 'Medical', 'Dentist'],
    colorScheme: {
      primary: '#059669',
      secondary: '#ecfdf5',
      accent: '#10b981',
      background: '#ffffff',
      text: '#065f46',
    },
  },
  {
    id: 'industry-legal-63',
    name: 'Legal Professional',
    category: 'Industry Specific',
    description: 'Law firm and legal services',
    layout: 'classic',
    industry: ['Legal', 'Law', 'Consulting'],
    colorScheme: {
      primary: '#1e3a8a',
      secondary: '#eff6ff',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1e40af',
    },
  },
  {
    id: 'industry-construction-64',
    name: 'Construction Builder',
    category: 'Industry Specific',
    description: 'Construction and contracting',
    layout: 'classic',
    industry: ['Construction', 'Building', 'Trades'],
    colorScheme: {
      primary: '#92400e',
      secondary: '#fed7aa',
      accent: '#f97316',
      background: '#ffffff',
      text: '#78350f',
    },
  },
  {
    id: 'industry-restaurant-65',
    name: 'Restaurant Hospitality',
    category: 'Industry Specific',
    description: 'Food service and hospitality',
    layout: 'elegant',
    industry: ['Restaurant', 'Food', 'Hospitality'],
    colorScheme: {
      primary: '#7c2d12',
      secondary: '#fef3c7',
      accent: '#d97706',
      background: '#ffffff',
      text: '#451a03',
    },
  },
  {
    id: 'industry-education-66',
    name: 'Education Academy',
    category: 'Industry Specific',
    description: 'Schools, universities, tutoring',
    layout: 'classic',
    industry: ['Education', 'School', 'Training'],
    colorScheme: {
      primary: '#5b21b6',
      secondary: '#f3e8ff',
      accent: '#a855f7',
      background: '#ffffff',
      text: '#2e1065',
    },
  },
  {
    id: 'industry-fitness-67',
    name: 'Fitness Wellness',
    category: 'Industry Specific',
    description: 'Gym, fitness, wellness centers',
    layout: 'modern',
    industry: ['Fitness', 'Wellness', 'Health'],
    colorScheme: {
      primary: '#dc2626',
      secondary: '#fee2e2',
      accent: '#f87171',
      background: '#ffffff',
      text: '#7f1d1d',
    },
  },
  {
    id: 'industry-photography-68',
    name: 'Photography Studio',
    category: 'Industry Specific',
    description: 'Photography and visual services',
    layout: 'creative',
    industry: ['Photography', 'Visual', 'Creative'],
    colorScheme: {
      primary: '#000000',
      secondary: '#f5f5f5',
      accent: '#808080',
      background: '#ffffff',
      text: '#000000',
    },
  },
  {
    id: 'industry-plumbing-69',
    name: 'Plumbing Trades',
    category: 'Industry Specific',
    description: 'Plumbing, electrical, HVAC',
    layout: 'classic',
    industry: ['Plumbing', 'Electrical', 'HVAC', 'Trades'],
    colorScheme: {
      primary: '#0369a1',
      secondary: '#e0f2fe',
      accent: '#0284c7',
      background: '#ffffff',
      text: '#164e63',
    },
  },
  {
    id: 'industry-beauty-70',
    name: 'Beauty Salon',
    category: 'Industry Specific',
    description: 'Beauty, salon, cosmetology',
    layout: 'elegant',
    industry: ['Beauty', 'Salon', 'Cosmetology'],
    colorScheme: {
      primary: '#be185d',
      secondary: '#fbcfe8',
      accent: '#ec4899',
      background: '#ffffff',
      text: '#831843',
    },
  },

  // ADDITIONAL VARIANTS (71-80)
  {
    id: 'variant-simple-71',
    name: 'Simple Minimal Pro',
    category: 'Minimal',
    description: 'Simple professional minimal',
    layout: 'minimal',
    industry: ['General', 'Professional'],
    colorScheme: {
      primary: '#374151',
      secondary: '#f9fafb',
      accent: '#6b7280',
      background: '#ffffff',
      text: '#1f2937',
    },
  },
  {
    id: 'variant-financial-72',
    name: 'Financial Services',
    category: 'Classic',
    description: 'Finance and banking template',
    layout: 'classic',
    industry: ['Finance', 'Banking', 'Insurance'],
    colorScheme: {
      primary: '#1e3a8a',
      secondary: '#dbeafe',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1e40af',
    },
  },
  {
    id: 'variant-startup-73',
    name: 'Startup Pitch',
    category: 'Modern',
    description: 'Startup and innovation focused',
    layout: 'modern',
    industry: ['Startup', 'Innovation', 'Tech'],
    colorScheme: {
      primary: '#7c3aed',
      secondary: '#f3e8ff',
      accent: '#a855f7',
      background: '#ffffff',
      text: '#2e1065',
    },
  },
  {
    id: 'variant-corporate-74',
    name: 'Enterprise Corporate',
    category: 'Classic',
    description: 'Large enterprise professional',
    layout: 'classic',
    industry: ['Corporate', 'Enterprise', 'B2B'],
    colorScheme: {
      primary: '#0f172a',
      secondary: '#f1f5f9',
      accent: '#64748b',
      background: '#ffffff',
      text: '#1e293b',
    },
  },
  {
    id: 'variant-creative-agency-75',
    name: 'Creative Agency Pro',
    category: 'Creative',
    description: 'Creative agency portfolio style',
    layout: 'creative',
    industry: ['Agency', 'Creative', 'Design'],
    colorScheme: {
      primary: '#f97316',
      secondary: '#fed7aa',
      accent: '#ea580c',
      background: '#ffffff',
      text: '#92400e',
    },
  },
  {
    id: 'variant-nonprofit-76',
    name: 'Nonprofit Organization',
    category: 'Classic',
    description: 'Nonprofit and charity invoices',
    layout: 'classic',
    industry: ['Nonprofit', 'Charity', 'NGO'],
    colorScheme: {
      primary: '#059669',
      secondary: '#ecfdf5',
      accent: '#10b981',
      background: '#ffffff',
      text: '#065f46',
    },
  },
  {
    id: 'variant-consulting-77',
    name: 'Consulting Expert',
    category: 'Professional',
    description: 'Management and business consulting',
    layout: 'classic',
    industry: ['Consulting', 'Business', 'Management'],
    colorScheme: {
      primary: '#1e293b',
      secondary: '#f1f5f9',
      accent: '#64748b',
      background: '#ffffff',
      text: '#0f172a',
    },
  },
  {
    id: 'variant-ecommerce-78',
    name: 'E-Commerce Store',
    category: 'Modern',
    description: 'Online retail and e-commerce',
    layout: 'modern',
    industry: ['E-commerce', 'Retail', 'Shopping'],
    colorScheme: {
      primary: '#dc2626',
      secondary: '#fee2e2',
      accent: '#f87171',
      background: '#ffffff',
      text: '#7f1d1d',
    },
  },
  {
    id: 'variant-freelance-79',
    name: 'Freelancer Pro',
    category: 'Modern',
    description: 'Freelancers and independent workers',
    layout: 'modern',
    industry: ['Freelance', 'Independent', 'Creative'],
    colorScheme: {
      primary: '#0284c7',
      secondary: '#e0f2fe',
      accent: '#0ea5e9',
      background: '#f8fafc',
      text: '#1e293b',
    },
  },
  {
    id: 'variant-premium-service-80',
    name: 'Premium Service',
    category: 'Elegant',
    description: 'Premium and luxury services',
    layout: 'elegant',
    industry: ['Luxury', 'Premium', 'High-end'],
    colorScheme: {
      primary: '#78350f',
      secondary: '#fef3c7',
      accent: '#d97706',
      background: '#fffbeb',
      text: '#451a03',
    },
  },
];

export const getTemplateById = (id: string): InvoiceTemplate | undefined => {
  return INVOICE_TEMPLATES.find((t) => t.id === id);
};

export const getTemplatesByCategory = (category: string): InvoiceTemplate[] => {
  return INVOICE_TEMPLATES.filter((t) => t.category === category);
};

export const getTemplatesByIndustry = (industry: string): InvoiceTemplate[] => {
  return INVOICE_TEMPLATES.filter((t) => t.industry.includes(industry));
};

export const getTemplateCategories = (): string[] => {
  return Array.from(new Set(INVOICE_TEMPLATES.map((t) => t.category)));
};

export const searchTemplates = (query: string): InvoiceTemplate[] => {
  const q = query.toLowerCase();
  return INVOICE_TEMPLATES.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.industry.some((ind) => ind.toLowerCase().includes(q))
  );
};
